[package]
name = "dpsa4fl"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
janus_client = { version = "0.1.13" }
janus_core = { version = "0.1.13" }
janus_messages = { version = "0.1.13" }
url = { version = "2.3.1" }
anyhow = "1.0"
reqwest = "0.11.12"
